mail:
  admin-email: niki10222@bk.ru
  from: smtp.tests.zuevc@gmail.com
  host: smtp.gmail.com
  password: Glass71836
  port: 587
  protocol: smtp
  smtp:
    auth: true
    debug: true
    starttls.enable: true
    starttls.required: true
  username: smtp.tests.zuev@gmail.com
server:
  port: 8080
  tomcat:
    threads:
      max: 15
      min-spare: 10
    max-connections: 50000
    accept-count: 10000
    accesslog:
      enabled: true
      buffered: false
      directory: logs
    basedir: logs
services:
  delivery:
    uri: http://localhost:8082
  payment:
    uri: http://localhost:8084
spring:
  datasource:
    password: ${DB_PASSWORD:300800}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orders}
    username: ${DB_USERNAME:postgres}
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    active: prod
