server:
  port: 8080

spring:
  profiles:
    active: prod
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orders}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:300800}
  jpa:
    hibernate:
      ddl-auto: create

services:
  payment:
    uri: 'http://localhost:8084'
  delivery:
    uri: 'http://localhost:8082'