server:
  port: 8081

spring:
  profiles:
    active: prod
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/payments}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:300800}
  jpa:
    hibernate:
      ddl-auto: create
